# Site settings
title: Html-coder/frontend-developer bvvell
email: vvbernacky@gmail.com
  description: > # this means to ignore newlines until "baseurl:"
   HTML coder / Front end developer. Freelance. HTML template creator. Best practices
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://html-coder.net" # the base hostname & protocol for your site
twitter_username: bvvell
github_username:  bvvell

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
